INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, collection_id, type_id, stage_id) VALUES
(120, 'Charizard', 'Flame Pokémon, evolves from Charmeleon', 'Fire Spin', '100', 'Water', 1, 1, 3),
(90, 'Blastoise', 'Shellfish Pokémon, evolves from Wartortle', 'Hydro Pump', '60', 'Electric', 1, 2, 3),
(60, 'Pikachu', 'Mouse Pokémon, mascot of the franchise', 'Thunder Jolt', '30', 'Fighting', 1, 4, 1),
(70, 'Snorlax', 'Sleeping Pokémon, known for blocking paths', 'Body Slam', '30', 'Fighting', 2, 6, 1),
(80, 'Aerodactyl', 'Fossil Pokémon revived from Old Amber', 'Wing Attack', '30', 'Electric', 3, 6, 1),
(50, 'Bulbasaur', 'Seed Pokémon, starter from Kanto', 'Vine Whip', '20', 'Fire', 1, 3, 1),
(60, 'Ivysaur', 'Seed Pokémon, evolves from Bulbasaur', 'Razor Leaf', '30', 'Fire', 1, 3, 2),
(80, 'Venusaur', 'Seed Pokémon, evolves from Ivysaur', 'Solar Beam', '60', 'Fire', 1, 3, 3),
(40, 'Charmander', 'Lizard Pokémon, starter from Kanto', 'Ember', '30', 'Water', 1, 1, 1),
(60, 'Charmeleon', 'Flame Pokémon, evolves from Charmander', 'Flamethrower', '50', 'Water', 1, 1, 2),
(50, 'Squirtle', 'Tiny Turtle Pokémon, starter from Kanto', 'Bubble', '20', 'Electric', 1, 2, 1),
(70, 'Wartortle', 'Turtle Pokémon, evolves from Squirtle', 'Water Gun', '40', 'Electric', 1, 2, 2),
(40, 'Jigglypuff', 'Balloon Pokémon, sings opponents to sleep', 'Sing', '0', 'Psychic', 2, 5, 1),
(60, 'Clefable', 'Fairy Pokémon, evolves from Clefairy', 'Metronome', '40', 'Psychic', 2, 5, 2),
(100, 'Hitmonlee', 'Kicking Pokémon, martial arts fighter', 'High Jump Kick', '50', 'Psychic', 2, 6, 1),
(100, 'Hitmonchan', 'Punching Pokémon, martial arts fighter', 'Special Punch', '50', 'Psychic', 2, 6, 1),
(70, 'Electabuzz', 'Electric Pokémon, known for strong punches', 'Thunder Punch', '30', 'Fighting', 2, 4, 1),
(90, 'Magmar', 'Spitfire Pokémon, fiery battler', 'Smokescreen', '40', 'Water', 2, 1, 1),
(60, 'Gastly', 'Gas Pokémon, ghostly presence', 'Lick', '10', 'Psychic', 3, 5, 1),
(80, 'Haunter', 'Gas Pokémon, evolves from Gastly', 'Nightmare', '30', 'Psychic', 3, 5, 2);