INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, collection_id, type_id, stage_id) VALUES
(50, 'Meowth', 'Scratch Cat Pokémon', 'Scratch', '20', 'Fighting', 2, 6, 1),
(70, 'Persian', 'Classy Cat Pokémon, evolves from Meowth', 'Slash', '30', 'Fighting', 2, 6, 2),
(60, 'Eevee', 'Evolution Pokémon with many evolutions', 'Quick Attack', '20', 'Fighting', 2, 6, 1),
(70, 'Vaporeon', 'Water evolution of Eevee', 'Water Gun', '30', 'Electric', 2, 2, 2),
(70, 'Jolteon', 'Electric evolution of Eevee', 'Thunder Shock', '30', 'Fighting', 2, 4, 2),
(70, 'Flareon', 'Fire evolution of Eevee', 'Flamethrower', '40', 'Water', 2, 1, 2),
(60, 'Oddish', 'Weed Pokémon', 'Absorb', '10', 'Fire', 2, 3, 1),
(70, 'Gloom', 'Weed Pokémon, evolves from Oddish', 'Poison Powder', '20', 'Fire', 2, 3, 2),
(90, 'Vileplume', 'Flower Pokémon, evolves from Gloom', 'Petal Dance', '40', 'Fire', 2, 3, 3),
(50, 'Cubone', 'Lonely Pokémon', 'Bone Club', '20', 'Grass', 3, 6, 1),
(80, 'Marowak', 'Bone Keeper Pokémon, evolves from Cubone', 'Bonemerang', '30', 'Grass', 3, 6, 2),
(60, 'Zubat', 'Bat Pokémon', 'Leech Life', '10', 'Electric', 3, 6, 1),
(70, 'Golbat', 'Bat Pokémon, evolves from Zubat', 'Wing Attack', '30', 'Electric', 3, 6, 2),
(90, 'Muk', 'Sludge Pokémon, evolves from Grimer', 'Sludge', '40', 'Psychic', 3, 5, 2),
(60, 'Grimer', 'Sludge Pokémon', 'Pound', '20', 'Psychic', 3, 5, 1),
(100, 'Lapras', 'Transport Pokémon', 'Water Gun', '40', 'Electric', 3, 2, 1),
(70, 'Krabby', 'River Crab Pokémon', 'Vice Grip', '20', 'Electric', 3, 2, 1),
(80, 'Kingler', 'Pincer Pokémon, evolves from Krabby', 'Crabhammer', '50', 'Electric', 3, 2, 2),
(60, 'Horsea', 'Dragon Pokémon', 'Smokescreen', '10', 'Electric', 3, 2, 1),
(70, 'Seadra', 'Dragon Pokémon, evolves from Horsea', 'Water Gun', '30', 'Electric', 3, 2, 2),
(90, 'Dragonair', 'Dragon Pokémon, evolves from Dratini', 'Slam', '40', 'Ice', 1, 6, 2),
(120, 'Dragonite', 'Dragon Pokémon, evolves from Dragonair', 'Hyper Beam', '70', 'Ice', 1, 6, 3),
(40, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', 1, 3, 1),
(60, 'Metapod', 'Cocoon Pokémon, evolves from Caterpie', 'Stiffen', '0', 'Fire', 1, 3, 2),
(80, 'Butterfree', 'Butterfly Pokémon, evolves from Metapod', 'Whirlwind', '30', 'Fire', 1, 3, 3),
(50, 'Weedle', 'Hairy Bug Pokémon', 'Poison Sting', '10', 'Fire', 1, 3, 1),
(60, 'Kakuna', 'Cocoon Pokémon, evolves from Weedle', 'Harden', '0', 'Fire', 1, 3, 2),
(80, 'Beedrill', 'Poison Bee Pokémon, evolves from Kakuna', 'Twineedle', '30', 'Fire', 1, 3, 3),
(70, 'Machop', 'Superpower Pokémon', 'Low Kick', '20', 'Psychic', 1, 6, 1),
(90, 'Machoke', 'Superpower Pokémon, evolves from Machop', 'Karate Chop', '40', 'Psychic', 1, 6, 2);