INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, collection_id, type_id, stage_id) VALUES
(40, 'Abra', 'Psi Pokémon', 'Teleport', '0', 'Psychic', 1, 5, 1),
(60, 'Kadabra', 'Psi Pokémon, evolves from Abra', 'Confusion', '30', 'Psychic', 1, 5, 2),
(80, 'Alakazam', 'Psi Pokémon, evolves from Kadabra', 'Psychic', '40', 'Psychic', 1, 5, 3),
(50, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '20', 'Fighting', 1, 4, 1),
(60, 'Magneton', 'Magnet Pokémon, evolves from Magnemite', 'Selfdestruct', '60', 'Fighting', 1, 4, 2),
(70, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', 1, 6, 1),
(80, 'Raticate', 'Mouse Pokémon, evolves from Rattata', 'Super Fang', '40', 'Fighting', 1, 6, 2),
(50, 'Poliwag', 'Tadpole Pokémon', 'Bubble', '10', 'Electric', 1, 2, 1),
(60, 'Poliwhirl', 'Tadpole Pokémon, evolves from Poliwag', 'Water Gun', '30', 'Electric', 1, 2, 2),
(90, 'Poliwrath', 'Tadpole Pokémon, evolves from Poliwhirl', 'Hydro Pump', '50', 'Electric', 1, 2, 3),
(40, 'Diglett', 'Mole Pokémon', 'Dig', '10', 'Grass', 1, 6, 1),
(60, 'Dugtrio', 'Mole Pokémon, evolves from Diglett', 'Earthquake', '40', 'Grass', 1, 6, 2),
(70, 'Geodude', 'Rock Pokémon', 'Tackle', '20', 'Grass', 3, 6, 1),
(80, 'Graveler', 'Rock Pokémon, evolves from Geodude', 'Rock Throw', '30', 'Grass', 3, 6, 2),
(100, 'Golem', 'Megaton Pokémon, evolves from Graveler', 'Explosion', '60', 'Grass', 3, 6, 3),
(60, 'Onix', 'Rock Snake Pokémon', 'Rock Throw', '30', 'Grass', 3, 6, 1),
(50, 'Drowzee', 'Hypnosis Pokémon', 'Pound', '20', 'Psychic', 1, 5, 1),
(70, 'Hypno', 'Hypnosis Pokémon, evolves from Drowzee', 'Meditate', '30', 'Psychic', 1, 5, 2),
(60, 'Koffing', 'Poison Gas Pokémon', 'Smog', '20', 'Psychic', 3, 5, 1),
(80, 'Weezing', 'Poison Gas Pokémon, evolves from Koffing', 'Explosion', '60', 'Psychic', 3, 5, 2),
(50, 'Seel', 'Sea Lion Pokémon', 'Headbutt', '20', 'Electric', 3, 2, 1),
(80, 'Dewgong', 'Sea Lion Pokémon, evolves from Seel', 'Aurora Beam', '40', 'Electric', 3, 2, 2),
(60, 'Tentacool', 'Jellyfish Pokémon', 'Poison Sting', '10', 'Psychic', 3, 2, 1),
(80, 'Tentacruel', 'Jellyfish Pokémon, evolves from Tentacool', 'Wrap', '30', 'Psychic', 3, 2, 2),
(70, 'Chansey', 'Egg Pokémon', 'Double-Edge', '80', 'Fighting', 1, 6, 1),
(90, 'Kangaskhan', 'Parent Pokémon', 'Comet Punch', '40', 'Fighting', 2, 6, 1),
(60, 'Paras', 'Mushroom Pokémon', 'Scratch', '20', 'Fire', 2, 3, 1),
(70, 'Parasect', 'Mushroom Pokémon, evolves from Paras', 'Spore', '30', 'Fire', 2, 3, 2),
(100, 'Scyther', 'Mantis Pokémon', 'Slash', '40', 'Fire', 2, 3, 1),
(90, 'Pinsir', 'Stag Beetle Pokémon', 'Guillotine', '50', 'Fire', 2, 6, 1);